### PR TITLE
simplify file iterator by delegating to bashlib input-files

### LINKED ISSUE #75: Do not create or remove folder if no input images

### PR DESCRIPTION
**Pull request by bertsky**
Depends on https://github.com/OCR-D/core/pull/753

Opens the path for a fix for #77

### CODE REVIEW

**Comment by bertsky** [comment]
CI:
```
ERROR: ocrd/core is too old (2.28.0 < 2.29.0). Please update OCR-D/core
```
this is expected. We have to wait for the update in core.

**Comment by bertsky** [comment]
Rerunning CI :crossed_fingers:

**Review by kba — APPROVED** [review]
What an improvement in readability and robustness :+1: Great work, also on the core release that enables it.

**Comment by bertsky** [comment]
Thanks – next I'll apply the same recipe to the other bashlib modules one by one.

**Pull request merged**
