### PR TITLE
Replace Apache License by GPL 2.0

### PR DESCRIPTION
**Pull request by stweil**
This fixes the license and is required because olena uses GPL 2.0.

### CODE REVIEW

**Review by kba — CHANGES_REQUESTED** [review]
Agreed in principle, any reason for replacing `LICENSE` with` COPYING`? We use the former in other OCR-D projects.

**Comment by stweil** [comment]
I have no personal preference. Many projects with GPL use COPYING, but I just tested that a new project in GitHub with GPL will get a LICENSE file. I'll update the PR accordingly.

**Comment by stweil** [comment]
The pull request was now updated and keeps the filename `LICENSE`.

**Comment by kba** [comment]
Thanks!

**Review by kba — APPROVED** [review]

**Pull request merged**
