### PR TITLE
Avoid failing rebuild of milena/mln/version.hh

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by bertsky** [comment]
@stweil Can you please look at the CI failure?

```
sed: can't read /home/travis/build/OCR-D/ocrd_olena/repo/olena/milena//home/travis/build/OCR-D/ocrd_olena/repo/olena/milena/mln/version.hh.in: No such file or directory
```

Looks like an absolute path got concatenated instead of a relative path. But isn't this exactly what this PR set out to fix?

**Comment by kba** [comment]
https://github.com/OCR-D/olena/pull/2

**Comment by bertsky** [comment]
I'd like to merge, but not until CI succeeds, and I have no permissions to trigger rebuild (neither Travis nor Circle).

**Comment by stweil** [comment]
Maybe this PR is no longer needed with Konstantin's fix for Olena.

**Comment by bertsky** [comment]
> Maybe this PR is no longer needed with Konstantin's fix for Olena.

Can you verify/falsify this somehow?

**Comment by stweil** [comment]
I just tried it on macOS, and it works, so I close this PR.

**Pull request closed without merging**
