### PR TITLE
Avoid build errors with recent compilers

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by bertsky** [comment]
Wow, is that all that's necessary to be able to compile with GCC>7?

**Comment by stweil** [comment]
Yes, that's all. I also have a fix for the configure problem. PR will follow.

**Comment by bertsky** [comment]
> Yes, that's all.

Excellent! (Maybe you want to add this to your [corresponding issue](https://gitlab.lrde.epita.fr/olena/olena/issues/5)).

> I also have a fix for the configure problem.

I'm all ears.

**Comment by stweil** [comment]
I added a commit which works around the configure problem. It works for me with recent versions of automake. Let's see whether it works with Travis CI, too.

**Comment by stweil** [comment]
The modified `configure` works in Travis CI, too. So this PR is ready for merging.

**Comment by bertsky** [comment]
> I added a commit which works around the configure problem. It works for me with recent versions of automake.

Excellent, thanks @stweil ! 

I've just tested with automake 1.16.1 and gcc 9.2.1 (the default in Ubuntu 19.10) – everything runs smoothly. I will add a commit removing the disclaimer from the README.

> Let's see whether it works with Travis CI, too.

That's expected: our Travis does not specify an OS or version for the job, so the default (which currently is Ubuntu Xenial) gets used, which was old enough already. Maybe we should add a second (harder) configuration based on a more recent distro. But the most recent still is Bionic...

**Comment by bertsky** [comment]
@kba I'd like to add a GH action for building and publishing the docker images under the `ocrd` DH account, but I don't have the credentials. Would you mind adding them to the project's _secrets_? Or would you prefer manual builds/pushes? (If so, please do!)

**Pull request merged**
