### PR TITLE
sauvola-ms* need different k at each scale

### PR DESCRIPTION
**Pull request by bertsky**
(so multiply to compensate to keep common default)

### CODE REVIEW

**Comment by bertsky** [comment]
Note: this needs updates for the test assets as well. (Since the implementation will now correctly use different `k` values for different scales, which is better but different.)

@kba do you want me to PR assets or is this bad timing (plus I still have problems with generating correct bag checksums)?

**Comment by bertsky** [comment]
Here is a comparison of the harder example provided by @jbarth-ubhd:

- original: 
ocrd-binarize2 orig
- `sauvola-ms-split` with old (all-k) behaviour and default (0.34):
ocrd-binarize2 sauvola-ms-split
- `sauvola-ms-split` with old (all-k) behaviour and reduced threshold (0.05):
ocrd-binarize2 sauvola-ms-split-all-0 05
- `sauvola-ms-split` with new (k2, k3, k4) behaviour and default (0.2, 0.3, 0.5):
OCR-D-BIN2_0001-BIN_sauvola-ms-split
- `sauvola-ms-split` with new (k2, k3, k4) behaviour and reduced threshold (0.05/0.34 * 0.2,0.3,0.5):
OCR-D-BIN_0001-BIN_sauvola-ms-split

**Review by kba — APPROVED** [review]

**Comment by kba** [comment]
The test image needs an update tho

**Comment by jbarth-ubhd** [comment]
@bertsky: I assume the factor 0.05/0.34 = 0.147 is applied to k2=0.2 & k3=0.3 & k4=0.5 ?

But where does the 0.05 come from?

**Comment by jbarth-ubhd** [comment]
> The test image needs an update tho

Is »tho« the middle english? Sorry, don't understand...

**Comment by kba** [comment]
> Is »tho« the middle english?

"tho" is short for "though", I just wanted to say that the test image is now out-of-date and needs updating before merge.

**Comment by bertsky** [comment]
> The test image needs an update tho

@kba see [above](https://github.com/OCR-D/ocrd_olena/pull/49#issuecomment-611106138)

**Comment by bertsky** [comment]
> I assume the factor 0.05/0.34 = 0.147 is applied to k2=0.2 & k3=0.3 & k4=0.5 ?

@jbarth-ubhd Exactly. The 0.2/0.3/0.5 scheme is the default in [Lazzara and Géraud's 2013](https://link.springer.com/article/10.1007/s10032-013-0209-0) multiscale paper (determined emprically to be "best" there). It's what had been defunct in the Olena implementation for several years now (apparently [by accident](https://gitlab.lrde.epita.fr/olena/olena/-/merge_requests/4#note_15653)).

> But where does the 0.05 come from?

From our discussion in the Gitter lobby on Mar 6 about your above example. (Remember, I tried to get a good result for it and reduced the `k` threshold until I got acceptable results. Then I compared with default `k` but `textcleaner` preprocessing, which turned out to be roughly equivalent.)

**Comment by bertsky** [comment]
> Note: this needs updates for the test assets as well. (Since the implementation will now correctly use different `k` values for different scales, which is better but different.)
> 
> @kba do you want me to PR assets or is this bad timing (plus I still have problems with generating correct bag checksums)?

@kba?

**Comment by kba** [comment]
> @kba do you want me to PR assets or is this bad timing (plus I still have problems with generating correct bag checksums)?

PR to assets welcome, I can fix the bag checksums.

**Pull request merged**
