### PR TITLE
fix handling input fileGrps where PAGE is mixed with derived images:

### LINKED ISSUE #65: remove Travis CI
See https://travis-ci.org/github/OCR-D/ocrd_olena/builds/713616420.

I think https://github.com/OCR-D/ocrd_olena/blob/master/.travis.yml is missing a `make install`. I have absolutely no idea why this wasn't noticed earlier.

### LINKED ISSUE #67: cannot cope with input in OCR-D/spec#164 convention
The Python-based processors get this for free, because the logic is now part of `Processor.input_files`: we have to adapt our bash wrappers such that if for some pageId there is both a PAGE and any number of images, the images get ignored. (Currently, they are treated as input, lifting them to new pages of the same name.)

### PR DESCRIPTION
**Pull request by bertsky**
- aggregate a list of PAGE pages
- aggregate a list of multi-image pages
- when iterating through files, check if the current page
  has a PAGE file:
  - if so, skip if not a PAGE file
  - otherwise, raise an error if page has multiple images

Fixes #67

### CODE REVIEW

**Comment by bertsky** [comment]
CI failure is still https://github.com/OCR-D/ocrd_olena/issues/65#issuecomment-678088740 – I'm going to add a fix here

**Comment by bertsky** [comment]
@kba I think this pattern needs to be simplified by providing some page iterator (along the lines of `Processor.input_files`) in core's bashlib. We just cannot make this the required pattern for all bash processors – it's too complex, and it's still inefficient.

**Comment by kba** [comment]
> @kba I think this pattern needs to be simplified by providing some page iterator (along the lines of `Processor.input_files`) in core's bashlib. We just cannot make this the required pattern for all bash processors – it's too complex, and it's still inefficient.

I will have a look, so much boilerplate code defeats the purpose of a "simple" wrapper, agreed.

I'm wondering however, whether ocrd_wrap would be the better (more performative, easier to follow conventions, better to maintain) technological basis for ocrd_olena in the long run?

**Comment by bertsky** [comment]
> I'm wondering however, whether ocrd_wrap would be the better (more performative, easier to follow conventions, better to maintain) technological basis for ocrd_olena in the long run?

In the long run, yes, we could remove the OCR-D wrapper here, and concentrate on the added value of an encapsulated build for scribo-cli, including CI and Docker.

But having a simple yet non-trivial show-case for bashlib is a good thing, too. After all, it forces us to keep improving bashlib :-)

**Comment by bertsky** [comment]
> I will have a look, so much boilerplate code defeats the purpose of a "simple" wrapper, agreed.

Regardless, if you want to merge the modules following the new convention today, we need to merge this in the current state – otherwise ocrd_olena will not fit in (except if first step in the pipeline).

**Review by kba — APPROVED** [review]

**Pull request merged**
