### PR TITLE
Add new macro BUILD_DIR for build directory

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
This is required to allow changing the build directory, for example by OCR-D/ocrd_all.

**Comment by bertsky** [comment]
The CI failure seems to be a direct consequence of that change. I am guessing that Olena's build system is not prepared for the switch from relative to absolute path in line 89.

**Comment by stweil** [comment]
That code which updates milena/mln/version.hh looks strange. Luckily it is not needed, so it can be avoided by touching that file.

**Review by kba — APPROVED** [review]

**Comment by bertsky** [comment]
> That code which updates milena/mln/version.hh looks strange. Luckily it is not needed, so it can be avoided by touching that file.

I'm not convinced yet this is the right way to fix this...

**Comment by stweil** [comment]
It does not fix the problem, but it avoids it. The right way would require a change (and tests) in the olena repository.

**Comment by stweil** [comment]
@bertsky, @kba, do you want to merge this PR, or would you suggest another solution?

**Review by kba — COMMENTED** [review]
I'm still fine with the change. However, I'm currently investigating a permission issue for fresh clones, I'll merge once I'm sure this isn't related.

**Comment by kba** [comment]
> However, I'm currently investigating a permission issue for fresh clones, I'll merge once I'm sure this isn't related.

I cannot reproduce it. @cneud and @EEngl52 both ran into issues with `sudo make deps-ubuntu` but I can neither find a way to trigger the issue here or in the context of ocrd_all.

**Pull request merged**
