### PR TITLE
rework build system and subrepos

### PR DESCRIPTION
**Pull request by bertsky**

### CODE REVIEW

**Comment by bertsky** [comment]
This should give a much cleaner dependency to assets. Also, allows to directly use upstream Olena. Builds much faster, and including the (few) Python bindings – and futurized! (This should pave the way to adding Python 3 bindings for binarization as well.)

**Comment by bertsky** [comment]
Maybe we should use SWIG's `-py3` option instead of futurize? But on the other hand, adding bindings for binarization is still a lot of work (in the least, the image buffers of Pillow and Milena would have to be converted and copied). And we now know that Milena is already going to be replaced by [Pylene](https://gitlab.lrde.epita.fr/olena/pylene), a C++11 library which gets bound to Python via pybind11. According to their [plans](https://gitlab.lrde.epita.fr/olena/olena/issues/3#note_14652), Scribo will be ported to Pylene as well.

So, for the moment, shall I remove the Python bindings from the build altogether? (This would remove the SWIG dependency.)

**Comment by wrznr** [comment]
@kba Push

**Comment by bertsky** [comment]
That last commit broke the tests: I accidentally committed an old version of the assets. Redoing the commit...

**Comment by bertsky** [comment]
Another problem was that upstream Olena now already included some of my patches.

**Comment by bertsky** [comment]
> So, for the moment, shall I remove the Python bindings from the build altogether? (This would remove the SWIG dependency.)

I think it is better to reduce dependencies for now. When we do get a real perspective for Python bindings, we can still re-activate. Please review (and merge)!

**Pull request merged**
